spring.application.name=adfd06_rest_api

#1. Port
server.port=8082

#2 SQL Server Database configuration 
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ADFDDB;TrustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#3 JPA configuration
spring.jpa.hibernate.ddl-auto=update 
